### ISSUE TITLE
Theme font size not scaling with font scaling factor

### ISSUE THREAD

**Issue by SKUndef** [zagortenay333/ciliora-secunda-shell#2]
Hi,

i recently changed laptop with a FHD 14" one, on which i use font scaling factor (1.25) to set correct font dpi. Problem is that the theme is not scaling font sizes accordingly. Could be a solution using "em" units instead of "px" for font sizes?

Thanks!

**Comment by zagortenay333** [comment]
Does is work correctly on other themes?

Can't fix it now though, not on gnome-shell.

**Comment by SKUndef** [comment]
It scales correctly on default theme. I've tested changing all `font-size` occurencies from `px` unit to `em` unit, and it works quite well; but i don't know if i choose the correct sizes (eg. 12px -> 0.9em).
At the moment i still have notifications title/content fonts not scaled, any idea where i can set `font-size` for that too?

P.S. I've found other theme creators solving the same problem this way: https://github.com/adapta-project/adapta-gtk-theme/issues/33

**Comment by SKUndef** [comment]
I've just pulled your new commits on Ciliora Tertia repository, awesome job there ;-)

I suppose the same will be extended to Secunda, so i thank you in advance!

Cheers

**Comment by zagortenay333** [comment]
This can be closed now I guess.

**Comment by SKUndef** [comment]
Ok, but still changes to font-size unit in Tertia are not extended here ;-)

**Comment by zagortenay333** [comment]
What do you mean?

**Comment by zagortenay333** [comment]
Oh, just noticed. Not sure how I didn't notice it..

**Comment by zagortenay333** [comment]
Ok, shoulf be fixed now.

**Comment by SKUndef** [comment]
Thanks! :-)
